### PR TITLE
Proper exception messages #5

### LINKED ISSUE #5: Proper Exception Messages
- Exception in code should be properly and relevant status code including error message must be captured in response.
- Refactor the controllers to handle exceptions properly

### PR DESCRIPTION
**Pull request by sauravp1**
Added try and catch block and handle some cases where controller can raise exception

### CODE REVIEW

File: src/Controller/CustomerController.php [hunk 1]
```diff
@@ -32,21 +36,30 @@ public function __construct(CustomerRepository $customerRepository)
...
+                $lastName = $data["lastName"];
+                $email = $data["email"];
+                $phoneNumber = $data["phoneNumber"];
+            } catch (ErrorException $e) {
+                return new JsonResponse(["message" => "Enter value for all field"], Response::HTTP_BAD_REQUEST);
+            }
+
+            if (empty($firstName) || empty($lastName) || empty($email) || empty($phoneNumber)){
+                throw new NotFoundHttpException("Expecting mandatory parameters:");
+            }
```
Comment (srinidhibhat-practo) [inline src/Controller/CustomerController.php]: You can add these validation for `$data` itself. Instead of assigning to variable and then checking.
Something like this:
```suggestion
            if (empty($data["firstName"]) 
                || empty($data["lastName"]) 
                || empty($data["email"]) 
                || empty($data["phoneNumber"])) {
                throw new NotFoundHttpException("Expecting mandatory parameters:");
            }
            try {
                $firstName = $data["firstName"];
                $lastName = $data["lastName"];
                $email = $data["email"];
                $phoneNumber = $data["phoneNumber"];
            } catch (ErrorException $e) {
               ...
```

File: src/Controller/CustomerController.php [hunk 2]
```diff
@@ -32,21 +36,30 @@ public function __construct(CustomerRepository $customerRepository)
...
+                $firstName = $data["firstName"];
+                $lastName = $data["lastName"];
+                $email = $data["email"];
+                $phoneNumber = $data["phoneNumber"];
+            } catch (ErrorException $e) {
+                return new JsonResponse(["message" => "Enter value for all field"], Response::HTTP_BAD_REQUEST);
+            }
+
+            if (empty($firstName) || empty($lastName) || empty($email) || empty($phoneNumber)){
+                throw new NotFoundHttpException("Expecting mandatory parameters:");
```
Comment (srinidhibhat-practo) [inline src/Controller/CustomerController.php]: Check formatting in this function body. Seems like more spaces than needed

File: src/Controller/CustomerController.php [hunk 3]
```diff
@@ -55,38 +68,52 @@ public function addCustomer(Request $request): JsonResponse
...
-     */
-    public function getAllCustomers(): JsonResponse
-    {
-        $customers = $this->customerRepository->findAll();
-        $data = [];
+            $customer = $this->customerRepository->findOneBy(['id' => $id]);
 
-        foreach ($customers as $customer) {
-            $data[] = [
+            if ($customer == null) {
```
Comment (srinidhibhat-practo) [inline src/Controller/CustomerController.php]: Can make use of builtin methods like `is_null()` whenever possible.

File: src/Controller/OrderController.php [hunk 4]
```diff
@@ -37,89 +38,122 @@ public function __construct(OrdersRepository $orderRepository, ProductRepository
...
-        // $product = $this->productRepository->findOneBy(['id' => $product_id]);
-        
-        
-        // $price = $product->getPrice();
+        try {
+            $data = json_decode($request->getContent(), true);
+            // $data = json_decode($request->getContent(), true);
+    
+            // $temp = $request->getContent();
+            // $temp = json_decode($temp);
```
Comment (srinidhibhat-practo) [inline src/Controller/OrderController.php]: How did these comments appear again?

File: src/Controller/OrderController.php [hunk 5]
```diff
@@ -37,89 +38,122 @@ public function __construct(OrdersRepository $orderRepository, ProductRepository
...
     public function updateOrder($id, Request $request) :JsonResponse
     {
-        $order = $this->orderRepository->findOneBy(["id"=>$id]);
-        // $data = json_decode($request->getContent(), true);
-        $data = json_decode($request->getContent(), true);
-
-
+        try {
+            $order = $this->orderRepository->findOneBy(["id"=>$id]);
+            // $data = json_decode($request->getContent(), true);
```
Comment (srinidhibhat-practo) [inline src/Controller/OrderController.php]: Remove

File: src/Controller/OrderController.php [hunk 6]
```diff
@@ -37,89 +38,122 @@ public function __construct(OrdersRepository $orderRepository, ProductRepository
...
+    
+            if (!empty($data['customer_id'])){
+                // Response
+                $data["customer_id"]=$this->customerRepository->findOneBy(["id"=>$data["customer_id"]]);
+            }
+            if (!empty($data['product_id']))
+            {
+                $data["product_id"] = $this->productRepository->findOneBy(["id"=>$data["product_id"]]);
+            }
+
```
Comment (srinidhibhat-practo) [inline src/Controller/OrderController.php]: Remove blank line

File: src/Controller/OrderController.php [hunk 7]
```diff
@@ -37,89 +38,122 @@ public function __construct(OrdersRepository $orderRepository, ProductRepository
...
+        } catch (Exception $e) {
+            return new JsonResponse(["message" => $e->getMessage()]); 
         }
-
-        
-        $this->orderRepository->updateOrder($order, $data);
-        return new JsonResponse(["message"=> "Order updated with id number ".$id]);
     }
-}
+ }
```
Comment (srinidhibhat-practo) [inline src/Controller/OrderController.php]: Remove stray space

File: src/Controller/CustomerController.php (hunk 3 above)
Comment (sauravp1) [reply src/Controller/CustomerController.php]: i have replaced with is_null() now

File: src/Controller/OrderController.php (hunk 4 above)
Comment (sauravp1) [reply src/Controller/OrderController.php]: because it was outdated branch

File: src/Controller/OrderController.php (hunk 5 above)
Comment (sauravp1) [reply src/Controller/OrderController.php]: done

File: src/Controller/OrderController.php (hunk 7 above)
Comment (sauravp1) [reply src/Controller/OrderController.php]: done

File: src/Controller/CustomerController.php (hunk 2 above)
Comment (sauravp1) [reply src/Controller/CustomerController.php]: yeah, removed in next commit

**Review by srinidhibhat-practo — APPROVED** [review]
